### ISSUE TITLE
can not compile ffmpeglibrary!

### ISSUE THREAD

**Issue by DougZeng** [CainKernel/CainCamera#10]
My ndk is r16b.
E:\project\demo\CainCamera\ffmpeglibrary\src\main\cpp\cainmedia\cainfilters\YUV420PImageFilter.cpp
fatal error: 'GlShaders.h' file not found
fatal error: 'GlShaders.h' file not found
E:\project\demo\CainCamera\ffmpeglibrary\src\main\cpp\cainmedia\cainplayer\Demuxer.h
error: unknown linkage language
error: unknown linkage language
error: unknown linkage language
error: unknown linkage language
error: unknown linkage language
error: unknown linkage language

**Comment by CainKernel** [comment]
I have push a commit to sovle this bug. please pull refresh it.

**Comment by DougZeng** [comment]
ok
