### ISSUE TITLE
根据某点旋转的问题

### ISSUE THREAD

**Issue by lexuszhi1990** [CainKernel/CainCamera#102]
我看到 `fragment_face_reshape.glsl` 这个文件中 通过放大/缩小/拉升来实现 美颜的效果，比如
`vec2 curveWarp(vec2 textureCoord, vec2 originPosition, vec2 targetPosition, float radius)` ， 我想请教下，如果做一个旋转的效果，比如将眼睛旋转一定的角度，做成丹凤眼之类的效果，具体的实现思路是怎么样的？
谢谢

**Comment by lexuszhi1990** [comment]
搞定了，thx

**Comment by huutho-dev** [comment]
@lexuszhi1990 do you implement that ideal yet?
