### ISSUE TITLE
Face++SDK联网请求验证失败

### ISSUE THREAD

**Issue by fxjzzyo** [CainKernel/CainCamera#105]
Face++SDK联网请求验证失败，注册不了license了
我在Face++官网新注册了apiKey和apiSecret，替换代码里面的之后，发现无效。
错误代码401，官网说这个代表apiKey和apiSecret不一致，可是我就是复制粘贴过来的啊，不可能不一致啊。
总之就是人脸检测这一块用不了了。
求大佬快快更新啊啊啊啊，感谢了！

**Comment by CainKernel** [comment]
人脸SDK的注册流程请参照这个流程注册：
https://github.com/CainKernel/CainCamera/blob/master/document/introduction/facepp_register.md
