### ISSUE TITLE
关于视频录制动态贴纸的问题

### ISSUE THREAD

**Issue by ruijun** [CainKernel/CainCamera#11]
@CainKernel 
你好，想了解下视频录制的时候增加动态贴纸(例如抖音，快手效果)有木有什么实现方案呢？ 我看到项目里面`GLStickerFilter`有提到，是不是使用`GLStickerFilter`可以实现呢？

**Comment by CainKernel** [comment]
这个就相对简单很多了，只需要你图像的长宽比（4:3、16:9等），对你背景动态进行裁剪（计算好 mipmapCoordinate UV坐标）。图像inputTexture 和 下雨效果的贴纸mipmapTexture，直接用默认的Blend混合就行。fragment shader 就跟下面的一样，下面就是默认的混合效果。然后你用glTexSubImage2D更新mipmapTexture的数据就行，比如说你的背景动画是0.2s更新一次的，那么在应用层用Handler每隔0.2s更新一次mipmapTexture就行。
```
precision mediump float;
varying vec2 textureCoordinate;    // texture的uv坐标
varying vec2 mipmapCoordinate;     // mipmap经过透视变换到屏幕上的uv坐标

uniform sampler2D inputTexture;    // 原始Texture
uniform sampler2D mipmapTexture;   // 贴图Texture

void main()
{
    lowp vec4 sourceColor = texture2D(inputTexture, 1.0 - textureCoordinate);
    lowp vec4 mipmapColor = texture2D(mipmapTexture, mipmapCoordinate);
    // 混合处理，此时可以做各种混合处理，比如变换透明度，变换颜色等等
    gl_FragColor = mipmapColor * mipmapColor.a + sourceColor * (1.0 - mipmapColor.a);
}
```

**Comment by ruijun** [comment]
inputTexture 指视频图像 ？ 在应用层用Handler每隔0.2s获取下一张png图片，更新到mipmapTexture就可以了？

**Comment by CainKernel** [comment]
是的，就是这么简单，这个跟添加实时水印是同样效果的。只不过的TextureCoordinate的大小和位置不是全屏，并且不是动态的而已。动态贴纸的更新也是这么实现的，就是需要你动态去更新一张贴图，然后等着GPU渲染就好。

**Comment by CainKernel** [comment]
输入的原始图像，跟贴图混合渲染。所有的动态贴纸都是这么做渲染的，upload到mipmapTexture的方式则可以跟我的录制方案一样，另外开一个线程进行，这个要注意OpenGLES 的SharedContext了，不过这个你也可以不用，直接在OpenGLES的渲染线程里面更新贴纸的mipmapTexture。FaceU相机的动态贴纸渲染跟这个glsl也是差不多的。你用SnapDragon Profiler 截一张图片一步步调试就知道了。GPU部分的代码相对简单，动态贴纸的核心还是在应用层的处理策略上。除非你要加自定义的Blend混合了。gl_FragColor = mipmapColor * mipmapColor.a + sourceColor * (1.0 - mipmapColor.a); 这句就是默认的混合方式，跟你调用glBlend是同样的效果。自定义混合就是改这个地方。动态贴纸也是一样的，主要还是在mipmapCoordinate的计算上。这个要你在应用层算好位置的。另外， 支持三维透视变换的Vertex Shader 可以这么写：
```
uniform mat4 uMVPMatrix;        // 总变换矩阵
uniform mat4 uTexMatrix;        // 输入图像的缩放矩阵
attribute vec4 aPosition;       // 输入图像的位置坐标
attribute vec4 aTextureCoord;   // 输入图像纹理坐标

attribute vec4 aMipmapCoord;    // 贴纸在视锥体空间中的垂直于z轴的假想坐标

uniform int centerX;          // 贴纸处于屏幕的中心位置x
uniform int centerY;          // 贴纸处于屏幕的中心位置y

varying vec2 textureCoordinate; // 输出texture坐标
varying vec2 mipmapCoordinate;  // 输出mipmap坐标

/**
 * 计算贴纸投影到屏幕的UV坐标
 */
vec2 calculateUVPosition(vec4 modelPosition, mat4 mvpMatrix) {
    vec4 tmp = vec4(modelPosition);
    tmp = mvpMatrix * tmp; // gl_Position
    tmp /= tmp.w; // 经过这个步骤，tmp就是归一化标准坐标了.
    tmp = tmp * 0.5 + vec4(0.5f, 0.5f, 0.5f, 0.5f); // NDC坐标
    tmp += vec4(centerx, centerY, 0.5f, 0.5f);// 平移到贴纸中心
    return vec2(tmp.x, tmp.y); // 屏幕的UV坐标
}

void main() {
    // texture的坐标
    textureCoordinate = (uTexMatrix * aTextureCoord).xy;;
    // 变换矩阵
    mipmapCoordinate = calculateUVPosition(aMipmapCoord, uMVPMatrix);
    gl_Position = aPosition;
}
```
calculateUVPosition 方法是用来做计算经过透视变换到屏幕UV坐标的过程，这里省略掉了平移到世界坐标原点再做透视变换的过程。你也可以不要三维投影的过程，直接用下面的方式直接计算纯二维变换:
```
mipmapCoordinate = (uMVPMatrix * aMipmapCoord).xy;
```

**Comment by ruijun** [comment]
谢谢你的回答！！还有个问题想问下，渲染指定帧具体是怎样实现的呢？(比如抖音的滤镜特效，长按某种特效，渲染指定的帧，而不是渲染全部)

**Comment by CainKernel** [comment]
这个就非常麻烦了。这个得你自己根据实际情况自研基于FFmpeg的播放器来做，特效是解码输出后，再用OpenGLES来做渲染处理，FFmpeg的AVFilter达不到效率，然后按下手指的时候，记录当前渲染的pts，特效以及特效时长，再次播放到这里的时候，根据记录的pts和特效，进行渲染，合成阶段，跟录制差不多，都是经过GPU渲染以后，再读出图像数据，然后复用输出为mp4文件，音频部分需要跟音乐进行混合处理。



发自我的小米手机
在 Jimson Liang <notifications@github.com>，2018年4月19日 上午9:47写道：

谢谢你的回答！！还有个问题想问下，渲染指定帧具体是怎样实现的呢？(比如抖音的滤镜特效，长按某种特效，渲染指定的帧，而不是渲染全部)

**Comment by chenliming777** [comment]
您好， 我想咨询一下如何通过106个点计算贴纸的中心点呢(已知2个偏移量坐标以及旋转坐标),看到咱们代码内部有一个centerList貌似通过解析直接过来的，不知道没有centerList如何计算 。有时间帮忙回复一下，谢谢啦

**Comment by CainKernel** [comment]
centerList 就是基准中心点对应的关键点索引。比如鼻子类型的贴纸中心点是人脸关键点46的位置，胡须的话，则是鼻翼两侧的关键点82 和 83的中间值作为中心点。如果你不给中心点的话，你就要对贴纸进行分类了，因为脸颊、耳朵、鼻子、脖子等各个部位的基准中心点是不一样的。没有基准中心点，你就得加入贴纸类型进行判断。要不然你无法定位位置。
