### ISSUE TITLE
Face Effects not working

### ISSUE THREAD

**Issue by snajdovski** [CainKernel/CainCamera#110]
I do not understand Chinese but from what I have tested on 4 different devices Face Effect for bunny ears does not work, any option or suggestion?

**Comment by snajdovski** [comment]
Tested on Pixel 2 XL, Samsung Galaxy s7 Edge, LG G6 and Blackview R7

**Comment by CainKernel** [comment]
Face Effects is supported by facepp sdk, and i use a trial sdk, which has a limited number of users and use times. So, face effects working needs to register another API Key,  API Secret and bind bundle id for CainCamera, and then replace FaceppConstraints' API_KEY and API_SECRET for yourself, this is the registration process for CainCamera，you can reference it：
https://github.com/CainKernel/CainCamera/blob/master/document/introduction/facepp_registration_eng.md

This is the facepp sdk website:
https://www.faceplusplus.com
 
more information, you can reference facpp‘s github: 
https://github.com/FacePlusPlus/MegviiFacepp-Android-SDK

**Comment by snajdovski** [comment]
Ok, Thanks!
