### ISSUE TITLE
Android camerax bug

### ISSUE THREAD

**Issue by soham24** [CainKernel/CainCamera#112]
face detection result is not coming 
also when I updated androidx package, some methods were removed and code did not run

Thanks for this awesome work
god bless you

**Comment by soham24** [comment]
Hello

**Comment by CainKernel** [comment]
face detection needs to register facepp detection sdk api key and secret for yourself: https://github.com/CainKernel/CainCamera/blob/master/document/introduction/facepp_registration_eng.md

I have camera rendering processing a little while ago, maybe some function is not implement. i'm  busy to implement the function of composition in video edit page now, no time to do anything else.

**Comment by soham24** [comment]
I solved this by going back to previous commit
