### ISSUE TITLE
简书的教程还可以看吗？

### ISSUE THREAD

**Issue by zhangluustb** [CainKernel/CainCamera#120]
作者您好，简书的教程目前全部看不到了，之前学了一半，可以给我分享一下吗？多谢。 邮箱：632518615@qq.com

**Comment by CainKernel** [comment]
我的简书账号被盗了，文章被锁定了，这几天我抽时间把博客的文章导出来放到Github上吧。

**Comment by zhangluustb** [comment]
多谢大佬
