### ISSUE TITLE
这就尴尬了触犯某些条款

### ISSUE THREAD

**Issue by wanglijun93** [CainKernel/CainCamera#13]

**Comment by CainKernel** [comment]
主要是我现在的工作也是做相机开发。上司说工作期间不能公开任何相关的东西，包括自己业余时间写的Demo，除非我离职。我现在正在参考保密协议修改源码，过段时间也会离职了，到时候就不用担心这个问题了。

**Comment by hushengjun** [comment]
好吧，有些公司是有这个要求的
