### ISSUE TITLE
建议栏

### ISSUE THREAD

**Issue by shengjunhu** [CainKernel/CainCamera#131]
首先这个库很Nice，个人提小建议：

1. 最好附上APK文件

2. 使用Face++的人脸关键点检测不是很好毕竟它是商业化，下面推荐几个开源的都很不错
   a-[mediapipe](https://github.com/google/mediapipe)
   b-[ncnn](https://github.com/Tencent/ncnn)
   c-[MNN](https://github.com/alibaba/MNN)

**Comment by ff-frida** [comment]
我记得第一次下载代码编译的时候，各种下载依赖，然后网络又很差，搞一天才把项目跑起来，太痛苦了。

**Comment by shengjunhu** [comment]
> 我记得第一次下载代码编译的时候，各种下载依赖，然后网络又很差，搞一天才把项目跑起来，太痛苦了。

这个问题，你可以先修改你本地已有的依赖版本库，
当然作者有时间的话可以在项目根目录抽一个config.gradle, 全局控制各库的版本的依赖

**Comment by ljmkimqx** [comment]
我参考作者的代码写安卓项目，使用Camera2，现在想要集成mediapipe，发现项目框架搭好后，要集成mediapipe很难，mediapipe很多东西都封装好了，内部封装使用CameraX，内部也封装好了Opengl和EGL，导致和项目冲突很大

**Comment by soham24** [comment]
@ljmkimqx  您好先生，我正在尝试将camera2添加到这个项目中。 如果您向我展示您的实现代码，这将是一个很大的帮助。 我已经创建了 camera2controller 文件并尝试添加关于 cameraController 类的 camera2 方法
