### ISSUE TITLE
继承surfaceview实现 Camera.PreviewCallback, SurfaceHolder.Callback，却抓取不到图像，是个黑屏

### ISSUE THREAD

**Issue by JackyYanSquare** [CainKernel/CainCamera#17]
这是我在代码中的部分代码，最后再手机中显示的就是一个黑色的一个矩形图像 

    @Override
    public void surfaceCreated(SurfaceHolder holder) {
        start();
    }

    @Override
    public void surfaceChanged(SurfaceHolder holder, int format, int width, int height) {
        mWidth = width;
        mHeight = height;
    }

    @Override
    public void surfaceDestroyed(SurfaceHolder holder) {
        stop();
    }
public void start() {
        /*if (mCamera != null) {
            return;
        }*/

        // 自己修改的部分
        if (mCamera != null) {
            mCamera.setPreviewCallback(null);
            mCamera.stopPreview();
            mCamera.release();
            mCamera = null;
        }
        if (getParent() == null) {
            LinearLayout preview = (LinearLayout) ((LCoopEye) mContext).findViewById(R.id.eye_main);
            ViewGroup.LayoutParams lp = new ViewGroup.LayoutParams(128, 72);
            // LayoutParams lp = new LayoutParams(5, 5);
            this.setLayoutParams(lp);
            preview.addView(this);
        }
        // mRect = new Rect(0, 0, mWidth, mHeight);
        mCamera = Camera.open();
        mCamera.setDisplayOrientation(90);
        Camera.Parameters param = mCamera.getParameters();
        //param.setFocusMode(param.FOCUS_MODE_CONTINUOUS_VIDEO);
        param.setPreviewFormat(ImageFormat.NV21);

        // 设置预览大小
        param.setPreviewSize(mWidth, mHeight);
        // 设置图片大小
        param.setPictureSize(mWidth, mHeight);
        selectFrameRate(param);

        // 设置参数
        mCamera.setParameters(param);
        mCamera.setPreviewCallback(this);
        if (mAvail != null) {
            try {
                // mCamera.setPreviewTexture(mAvail);
                mCamera.setPreviewDisplay(mSurfaceHolder);
                this.setVisibility(VISIBLE);
                mCamera.startPreview();
                //this.setVisibility(INVISIBLE);
            } catch (IOException e) {
                Log.i(TAG, "setPreviewTexture fail", new Exception());
                return;
            }
        }
        parameters(mCamera);
        Log.i(TAG, "start");
    }
public void stop() {
        if (mCamera == null)
            return;
        mCamera.stopPreview();
        mCamera.setPreviewCallback(null);
        mCamera.release();
        mCamera = null;
        Log.i(TAG, "stop");
    }

    public void resume() {
        if (mCamera == null)
            return;
        //this.setVisibility(VISIBLE);
    }

    @Override
    public void onPreviewFrame(byte[] data, Camera camera) {
        // Log.i(TAG,"onPreviewFrame");
        Log.d(TAG, "onPreviewFrame: data的数据" + data.toString(), new Exception());

        Camera.Parameters parameters = camera.getParameters();
        int imageFormat = parameters.getPreviewFormat();        // 拿到默认格式
        Camera.Size size = camera.getParameters().getPreviewSize();
        int w = parameters.getPreviewSize().width; //拿到预览尺寸
        int h = parameters.getPreviewSize().height;
        Rect rect = new Rect(0, 0, w, h);
        // YuvImage image = new YuvImage(data, ImageFormat.NV21, mWidth, mHeight, null);
        YuvImage image = new YuvImage(data, imageFormat, w, h, null);
        ByteArrayOutputStream mJpegStream = new ByteArrayOutputStream();
        //image.compressToJpeg(mRect, 70, mJpegStream);
        image.compressToJpeg(rect, 70, mJpegStream);
        mDataListener.onData(mJpegStream.toByteArray());

        /*try {
            YuvImage yuvImage = new YuvImage(data, ImageFormat.NV21, size.width, size.height, null);
            Log.i("yuvImage", "onPreviewFrame: " + yuvImage.getYuvFormat());
            if (yuvImage != null) {
                ByteArrayOutputStream mJpegStream = new ByteArrayOutputStream();
                yuvImage.compressToJpeg(mRect, 70, mJpegStream);
                mJpegStream.flush();

                mDataListener.onData(mJpegStream.toByteArray());
            }
        } catch (Exception e) {
            Log.e("SYS", "Error:" + e.getMessage());
        }*/
    }

现在也不知道哪里错了……就是不出来照相机预览图像，求大神指点迷津

**Comment by CainKernel** [comment]
如果只是单纯用SurfaceView 显示Camera的数据的话，可以参考本人之前的文章[Android Camera SurfaceView 预览拍照](https://www.jianshu.com/p/9e0f3fc5a3b4)，里面有完整的代码。你对一下看看哪个地方有问题。对了，这里有个问题，好像在某些手机上面，setPreviewCallback要放在setPreviewDisplay 之后，要不然使用setPreviewCallback 以及setPReviewCallbackWidthBuffer方法的可能会导致 onPreviewFrame()没回调的情况。
