### ISSUE TITLE
关于特效视频保存的问题

### ISSUE THREAD

**Issue by ningsk** [CainKernel/CainCamera#23]
您好，目前针对如何给编辑的视频增加特效后，保存已编辑的视频，您有官方的方案吗？可不可以针对您现有的框架，给我提出一点可行性的建议呢？

**Comment by CainKernel** [comment]
是的，目前那些看着合成很快的方案都是这么搞的。跟视频本身时长相近就是因为重新播放，播放时重新录制一遍而已。因为如果要插入转场动画之类的，一帧一帧地处理是非常麻烦的，时间戳会跟音频的不一致，引入的问题会非常非常多，怎么同步都是个问题。但是重新录制一遍，我就能保证跟我预览的一样。就算为了更好地压缩大小，用x264 和 AAC软编码来做录制，时间也不会比硬编码长多少的。720P的视频只不过是做不到百分百实时软编码而已，但合成阶段我不丢帧，直接等待录制流程处理完数据播放器再播放就好，反正时间戳我能保证就行。这就是合成时间总是比视频时长一点的原因。
