### ISSUE TITLE
用你的ffmpeg  会有这种报错，该如何解决呢

### ISSUE THREAD

**Issue by ithour** [CainKernel/CainCamera#24]
![default](https://user-images.githubusercontent.com/18640117/49129395-98962780-f30a-11e8-9bd7-96d4164d6239.png)

**Comment by ithour** [comment]
调用项目里面视频转gif 时，没有gif输出查看log 只出现了
![default](https://user-images.githubusercontent.com/18640117/49130551-7bb02300-f30f-11e8-9873-af22c9fe96c4.png)

**Comment by CainKernel** [comment]
ffmpeglibrary我还没弄完整，我的libffmpeg.so删了好多东西。命令行这块，你去找找其他开源项目吧。我这边是不打算用命令行做视频编辑处理。命令行功能只是以前遗留下来的没经过测试的代码，建议你去参考其他人的开源项目，我计划移除FFmpeg命令行功能的，抱歉。
