### ISSUE TITLE
贴纸，美妆啥的都点了都没反应呀！

### ISSUE THREAD

**Issue by luluxiu2014** [CainKernel/CainCamera#26]
是需要自己重新弄个face＋＋的人脸识别sdk吗，直接跑你的工程好像已经没有反应了。

**Comment by CainKernel** [comment]
你到face++注册一个key，替换掉facedetectlibrary的FaceppConstraints里面API_KEY 和 API_SECRET即可。

**Comment by hu-ping** [comment]
你好，我到face++注册一个key，然后替换了facedetectlibrary的FaceppConstraints里面API_KEY 和 API_SECRET，使用猫脸还是没有效果。我购买了face++的调用次数，查询face++，发现调用失败。

**Comment by CainKernel** [comment]
官网注册了key，还需要绑定的Bundle ID，这个是给网络验证用的，Bundle ID 需要绑定报名com.cgfay.caincamera。如果你是用在你自己的应用中，请将包名改成你自己的。

**Comment by hu-ping** [comment]
试了，可以了，非常感谢！

**Comment by chongbo2013** [comment]
您好，静态贴纸，是需要，重新扩展还是现在已经有了

**Comment by lichangzi** [comment]
我替换了也没有反应，你这个说非联网验证什么意思
