### ISSUE TITLE
华为手机截屏没有图像

### ISSUE THREAD

**Issue by sgzs** [CainKernel/CainCamera#28]
/**
     * 获取当前帧的缓冲
     * @return
     */
    public ByteBuffer getCurrentFrame() {
        int width = getWidth();
        int height = getHeight();
        ByteBuffer buf = ByteBuffer.allocateDirect(width * height * 4);
        buf.order(ByteOrder.LITTLE_ENDIAN);
        GLES30.glReadPixels(0, 0, width, height,
                GLES30.GL_RGBA, GLES30.GL_UNSIGNED_BYTE, buf);
        OpenGLUtils.checkGlError("glReadPixels");
        buf.rewind();
        return buf;
    }
buf为数组为空

**Comment by CainKernel** [comment]
似乎华为手机都有这个问题 —— 
https://cn.club.vmall.com/thread-15136902-1-1.html
https://cn.club.vmall.com/thread-12292348-1-1.html
我手上没有华为相关的设备，不太清楚具体出现问题的原因，估计跟Mali GPU 或驱动层有关吧。个人猜测有以下几种可能—— 第一，驱动层有Bug，如果是这个原因，那应用层是没法解决的，得找华为的工程师要解决方案。第二，如果是GPU读取过慢导致的，这里大概率是OpenGL ES驱动缓冲区的命令没有加载的问题吧，你尝试用glFlush()，或者glFinish()看能否解决，不过glFlush()、glFinish() 都会导致预览帧率降低。另外还有一种解决方案，就是通过SharedContext 绘制需要截屏的内容输出到ImageReader中再做保存。你先看看以上几种思路能否解决你的问题？
