### ISSUE TITLE
如何获取相机预览的原始帧数据和美颜后的帧数据？

### ISSUE THREAD

**Issue by AlixChiong** [CainKernel/CainCamera#29]
如何获取相机预览的原始帧数据和美颜后的帧数据？在哪里获取？

**Comment by CainKernel** [comment]
原始数据在onPreviewFrame回调的数据就是相机原始数据，我这边用的是SurfaceTexture渲染的，美颜后的帧数据，在EglCore的有获取单帧的方法，预览拍照的代码就是这个

**Comment by CainKernel** [comment]
又是华为。。。我手上没有华为相关的设备，无法测试。华为的ROM自身存在不少的问题，前面有不少issue有提到过这个了。你可以先试试shareContext的方式截帧，利用ImageReader的Surface创建一个WindowSurface，makecurrent再做渲染，然后ImageReader填充完成再取出数据。目前除了glReadPixels方法外，没太好的办法。而且ImageReader存在尺寸限制。这个问题要想彻底解决，只能找华为的工程师找通用的解决方案。

**Comment by wanliang527** [comment]
onPreviewFrame回调的相机原始数据好像跟渲染后的单帧数据不同步？我尝试改造了RenderThread.drawFrame方法，如下：
 // 执行拍照
            if (mCameraParam.isTakePicture) {
                synchronized (mSyncFence) {
                    ByteBuffer buffer = mDisplaySurface.getCurrentFrame();
                    mCameraParam.captureCallback.onCapture(buffer,
                            mDisplaySurface.getWidth(), mDisplaySurface.getHeight());
                    mCameraParam.isTakePicture = false;
                    long start = System.currentTimeMillis();
                    Bitmap bitmap = new NV21ToBitmap(mContext).nv21ToBitmap(data, mCameraParam.previewWidth, mCameraParam.previewHeight);
                    BitmapUtils.bitmapToFile(bitmap, Bitmap.CompressFormat.JPEG, "mnt/sdcard/face_temp.jpg");
                }
            }
然而最终的结果是原始图片文件跟拍照后屏幕显示的图片是不一致的。

想请教一下，如何保证帧数据的同步？我需要同时取到原始相机数据和美颜渲染后的数据
