### ISSUE TITLE
获取不到人脸数量

### ISSUE THREAD

**Issue by AlixChiong** [CainKernel/CainCamera#30]
LandmarkEngine.getInstance().hasFace()始终为false和LandmarkEngine.getInstance().getFaceSize()始终为0，这是为什么呢

**Comment by CainKernel** [comment]
face++人脸sdk联网认证失败，由于试用版的使用次数有限导致的，你到face++官网注册另外一个key替换facedetectlibrary中FaceppConstraints对应的API_KEY 和 API_SECRET 看看

**Comment by AndroidJohnsonWang** [comment]
所以目前使用这个，需要face++付费对吧
