### ISSUE TITLE
编译不过去啊老哥，帮看看什么原因

### ISSUE THREAD

**Issue by wsliuguoqing** [CainKernel/CainCamera#33]
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.

The target system is: Android - 1 - armv7-a
The host system is: Windows - 10.0.14393 - AMD64

**Comment by CainKernel** [comment]
你的NDK有问题吧。我这边用Android Studio自动下载的NDK，在Android SDK 下的ndk-bundle目录。我这边windows、linux都测试过了，没有任何问题，MacOS由于没有设备没法测试。况且，NDK里的cmake 是自动设置CMAKE_MAKE_PROGRAM路径的，你重新下载一个NDK看看？？
