### ISSUE TITLE
请问录屏支持区域录屏吗

### ISSUE THREAD

**Issue by zhang20084** [CainKernel/CainCamera#34]
请问录屏支持区域录屏吗

**Comment by CainKernel** [comment]
区域录屏这个跟相机预览没啥关系，主要录制器里面做调整就好。你在录制时做裁剪渲染，同时MediaCodec设置录制的大小，SharedContext里面调整glViewport就能做到区域录制问题了，你想录多大的都行。简单来说就是把你需要录制的区域，绘制到与MediaCodec的Surface上，原来的纹理大小需要做裁剪处理。并不影响预览的逻辑啊，我这边用了SharedContext就是为了方便后续添加其他处理啊。
