### ISSUE TITLE
老哥ffmpeg  x264能提供是什么版本，怎么编译出错

### ISSUE THREAD

**Issue by chongbo2013** [CainKernel/CainCamera#39]
老哥ffmpeg  x264是什么版本，怎么编译出错

**Comment by CainKernel** [comment]
ffmpeg 和 x264 版本跟编译无关，跟编译环境有关，主要是不太建议使用windows环境进行编译ffmpeg。windows环境编译的问题太多了，建议使用Linux/MacOS编译。Windows环境编译不过是正常的，MingW编译出来的libffmpeg.so 会出现莫名其妙的内部崩溃，建议慎重使用。

**Comment by chongbo2013** [comment]
ok

**Comment by chongbo2013** [comment]
你的demo 视频导入 还没做 离屏渲染是吧，我看了点击 下一步好像没反应

**Comment by CainKernel** [comment]
暂时还没写完，现在在弄这个。

**Comment by chongbo2013** [comment]
666
