### ISSUE TITLE
Effect里面的类似抖音特效怎么使用

### ISSUE THREAD

**Issue by austin98x** [CainKernel/CainCamera#41]
看到有实现类似抖音的一些特效。相机里面怎么没有使用？怎么看这些特效？

**Comment by CainKernel** [comment]
我在相机里面没有用上，那些特效是跟时间相关的。使用的时候需要传一个时间戳进去。这部分内容我是打算放到短视频编辑页面去的。不过我现在把播放器弄得差不多了，打算放到Native层来渲染特效。这边估计得等我几天，我这几天正在做这块，估计三月上旬能完成短视频的全部功能了。

**Comment by microgogo** [comment]
那现在短视频编辑功能能用了么？

**Comment by CainKernel** [comment]
抱歉，裁剪和合成功能还没弄完，弄起来比较复杂，涉及的东西比较多。要弄完整的话，比较花时间就是。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: microgogo <notifications@github.com>
发送时间: Wednesday, March 27, 2019 5:36:41 PM
收件人: CainKernel/CainCamera
抄送: 黄文君; Comment
主题: Re: [CainKernel/CainCamera] Effect里面的类似抖音特效怎么使用 (#41)


那现在短视频编辑功能能用了么？

―
