### ISSUE TITLE
视频保存两遍

### ISSUE THREAD

**Issue by gaoqianZ** [CainKernel/CainCamera#42]
相同的视频录制完成后，在文件夹内会保存两个视频文件，请问这是怎么回事

**Comment by CainKernel** [comment]
应该是缓存没删吧，分段录制的时候会有几个小视频。这个我没删，你可以看一下是否这个原因。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: gaoqianZ <notifications@github.com>
发送时间: Monday, February 25, 2019 4:16:11 PM
收件人: CainKernel/CainCamera
抄送: Subscribed
主题: [CainKernel/CainCamera] 视频保存两遍 (#42)


相同的视频录制完成后，在文件夹内会保存两个视频文件，请问这是怎么回事

―

**Comment by gaoqianZ** [comment]
好的 我看下逻辑

**Comment by gaoqianZ** [comment]
按照我现在的需求，我把短视频监听的代码注释了 不会再保存两遍
