### ISSUE TITLE
预览界面底部为白色

### ISSUE THREAD

**Issue by gaoqianZ** [CainKernel/CainCamera#45]
Android8.0 三星note8 包括模拟器

我怀疑是屏幕比例问题 问题机型都是18.5:9
16:9的没有问题
![141551177497_ pic_hd](https://user-images.githubusercontent.com/22052035/53406937-ff081000-39f5-11e9-9d15-29368e5519ac.jpg)

**Comment by CainKernel** [comment]
我这边就弄了 4:3、16:9的比例，下面没数据当然是白色的啊。项目目前还没弄18:9等全屏的处理，默认使用的是16:9的比例。18:9等全屏比例的处理需要你自行实现验证处理。我这边暂时不对这些比例做处理，在忙着做短视频部分的功能呢。

**Comment by gaoqianZ** [comment]
明白了
