### ISSUE TITLE
唇彩的mask坐标点有工具可以直接生成吗？

### ISSUE THREAD

**Issue by liuhangb** [CainKernel/CainCamera#46]

**Comment by CainKernel** [comment]
唇彩mask坐标或者说彩妆的所有mask坐标，都只能根据你的实际情况自己实现构建工具，属于数据标注的一环吧。

**Comment by liuhangb** [comment]
感谢你的回复，另外还有个问题， 你demo中唇彩边缘没有实现平滑过渡效果，你知道哪里可以找到这方面的shader算法吗？

**Comment by CainKernel** [comment]
平滑过渡的话，一般会通过mask的alpha配合处理比较合适，shader的话，很难计算出不同方位角的嘴唇是怎样的形状啊。这个只能配合关键点来做处理。基本上各家的APP都是自己的方案。目前没有一个通用的方案。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: liuhangb <notifications@github.com>
发送时间: Wednesday, March 6, 2019 7:14:28 PM
收件人: CainKernel/CainCamera
抄送: 黄文君; Comment
主题: Re: [CainKernel/CainCamera] 唇彩的mask坐标点有工具可以直接生成吗？ (#46)


感谢你的回复，另外还有个问题， 你demo中唇彩边缘没有实现平滑过渡效果，你知道哪里可以找到这方面的shader算法吗？

―

**Comment by liuhangb** [comment]
通过mask的alpha调整，是在shader脚本中控制的吗？我目前刚学习不是很懂，不知道你这边有例子可以参考吗？

**Comment by CainKernel** [comment]
Mask一般不是黑白的图片吗？边沿部分带alpha 1 ~ 0渐变，然后做线性混合mix这样啊。就是标注的关键点可能要自己多搞几个，人脸关键点SDK给出来的数量不一定够用。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: liuhangb <notifications@github.com>
发送时间: Wednesday, March 6, 2019 7:29:37 PM
收件人: CainKernel/CainCamera
抄送: 黄文君; Comment
主题: Re: [CainKernel/CainCamera] 唇彩的mask坐标点有工具可以直接生成吗？ (#46)


通过mask的alpha调整，是在shader脚本中控制的吗？我目前刚学习不是很懂，不知道你这边有例子可以参考吗？

―
