### ISSUE TITLE
关于颜色查找表的问题

### ISSUE THREAD

**Issue by ruijun** [CainKernel/CainCamera#47]
@CainKernel 你好，我想问下滤镜用到的颜色查找表(如图)是怎样生成的呢？

![image](http://anddymao.com/img/post_filter_3.png)

**Comment by CainKernel** [comment]
通常情况下是利用Photoshop 调色，然后导出 3D LUT的图片。制作过程可以参考这篇文章 ―― https://www.jianshu.com/p/b470a5b5a560 我记得知乎上似乎也有人写过类似的教程。调好色彩之后，将原始512x512分辨率的lut图(可以在GPUImage中找到)替换背景图片，然后保存渲染后的lut图片，这个图片就是我们想要的lut 了。制作过程就是这么简单，基本上都是特效设计师的工作。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Jimson Liang <notifications@github.com>
发送时间: Thursday, March 7, 2019 3:01:03 PM
收件人: CainKernel/CainCamera
抄送: 黄文君; Mention
主题: [CainKernel/CainCamera] 关于颜色查找表的问题 (#47)


@CainKernel<https://github.com/CainKernel> 你好，我想问下滤镜用到的颜色查找表(如图)是怎样生成的呢？

[image]<https://camo.githubusercontent.com/007217b690155cda0a6fedc993d34a9554341f66/687474703a2f2f616e6464796d616f2e636f6d2f696d672f706f73745f66696c7465725f332e706e67>

―

**Comment by ruijun** [comment]
好的，我了解下。还有个问题要请教下你，设计师在PS上作出的滤镜效果，怎样可以快速在Android上实现对应的效果呢？ 比如动画可以用Lottie来做。

**Comment by CainKernel** [comment]
导出的LUT(颜色查找表)，可以直接使用OpenGLES来渲染实现，比较出名的就是GPUImage框架了，Android 和 iOS都有。你也可以自行实现。CainCamera这边就是自己另外弄得一套流程，你可以看本项目的filterlibrary 中的 GLImage512LookupTableFilter的实现，shader 来自GPUImage，是用来渲染512x512大小的LUT。另外也可以用C++甚至Java来实现，需要你自己实现3D LUT 的查找算法，就是根据不同颜色通道的值进行查找映射得到新的颜色值。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Jimson Liang <notifications@github.com>
发送时间: Thursday, March 7, 2019 3:25:04 PM
收件人: CainKernel/CainCamera
抄送: 黄文君; Mention
主题: Re: [CainKernel/CainCamera] 关于颜色查找表的问题 (#47)


好的，我了解下。还有个问题要请教下你，设计师在PS上作出的滤镜效果，怎样可以快速在Android上实现对应的效果呢？ 比如动画可以用Lottie来做。

―

**Comment by ruijun** [comment]
对于颜色查找表生成的问题，是不是可以这样理解==》在PS上对标准颜色查找表实现想要的滤镜效果，然后生成新的颜色查找表在Android上使用就可以了？

**Comment by CainKernel** [comment]
对的。512x512大小的标准颜色查找表，本身就是按照规则将RGB通道的0 ~ 256 色阶降阶成 0 ~ 64阶得到的图片(512x512 = R64 x G64 x B64)。对图片调整好滤镜之后，我们对标准颜色查找表做同样的操作，就得到了映射之后的LUT。其实就是把PS的处理结果保存到LUT的图片中而已。这样我们就不需要一步一步来复现ps的过程了，节省了不少时间。通过这种方式，我们就能够将滤镜应用到实时渲染当中了，比如直播、相机的实时滤镜。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Jimson Liang <notifications@github.com>
发送时间: Thursday, March 7, 2019 5:20:51 PM
收件人: CainKernel/CainCamera
抄送: 黄文君; Mention
主题: Re: [CainKernel/CainCamera] 关于颜色查找表的问题 (#47)


对于颜色查找表生成的问题，是不是可以这样理解==》在PS上对标准颜色查找表实现想要的滤镜效果，然后生成新的颜色查找表在Android上使用就可以了？

―

**Comment by ruijun** [comment]
256*3的颜色查找表也只这个原理嘛？

![](http://anddymao.com/img/post_filter_4.png)

**Comment by CainKernel** [comment]
这个是分RGB通道合成的1D LUT的应用。LUT有一个三阶，1D LUT 用来调整gamma，灰度映射等功能，大小256x1，2D LUT 主要用来调整饱和度亮度等，你见到那些的从左上角到右下角黑白渐变过渡的纹理就是2D LUT，这个在图片编辑的APP里面比较常见。3D LUT 就是我们之前说过的那些，用来调节比较复杂的处理。这里有一篇文章讲到一二三阶 LUT的区别 ―― https://blog.csdn.net/trent1985/article/details/81101688  256x3 的LUT并不属于3D LUT的范畴。你问的这些基本都是图像处理的基本知识，建议你去看冈萨雷斯的《数字图像处理 第三版》 第六章 彩色图像处理。这里介绍了色彩模型，灰度分层，色彩变换，RGB向量空间中的分割，以及书本翻开封面就能看到的彩图，你问的所有问题，基本上都是这一章的知识。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Jimson Liang <notifications@github.com>
发送时间: Thursday, March 7, 2019 6:08:03 PM
收件人: CainKernel/CainCamera
抄送: 黄文君; Mention
主题: Re: [CainKernel/CainCamera] 关于颜色查找表的问题 (#47)


256*3的颜色查找表也只这个原理嘛？

[https://camo.githubusercontent.com/eee69a95c49540ca7e9782b31571b8749f4a06f5/687474703a2f2f616e6464796d616f2e636f6d2f696d672f706f73745f66696c7465725f342e706e67]<https://camo.githubusercontent.com/eee69a95c49540ca7e9782b31571b8749f4a06f5/687474703a2f2f616e6464796d616f2e636f6d2f696d672f706f73745f66696c7465725f342e706e67>

―

**Comment by ruijun** [comment]
好的，谢谢。

**Comment by CastleCC** [comment]
512*512的颜色映射表由于压缩，无法完全复现PS的效果，对于比较细腻的纹理效果有点差，请问你知道有什么可行的更好的实现方式吗？
