### ISSUE TITLE
请问:nexus5X画面上下颠倒,该如何解决?

### ISSUE THREAD

**Issue by o03150** [CainKernel/CainCamera#5]

**Comment by CainKernel** [comment]
旧的Camera API 似乎是解决不了这个问题的，传感器值缺少，不知道相机的实际方向，Android 5.0以前的Camera API是没考虑过摄像头还有不同的转配方式的，不过只有google系列的手机会存在这样的问题。更换成Camera2 接口，或者直接强制记录bullhead 和 nexus 5X的名称，手动倒置，否则旧API 是做不到的

**Comment by o03150** [comment]
感谢解答
