### ISSUE TITLE
onPreviewFrame 和 onFrameAvailable 回调的时序问题

### ISSUE THREAD

**Issue by Greatkingcj** [CainKernel/CainCamera#50]
@CainKernel 你好， 我看到在RenderThread中，你是收到相机的回调方法onPreviewFrame之后调用requestRender，然后开始drawFrame的，在drawFrame中调用了updateTexImage。但是updateTexImage需要在SurfaceTexture的一帧数据可用之后调用。这里能够保证onFrameAvailable在相机回调onPreviewFrame之前就被调用了吗？

**Comment by CainKernel** [comment]
onPreviewFrame 和 onFrameAvailable 的先后顺序并不一定能得到保证。通常情况下都是onFrameAvailable要快一点，因为数据帧在Native层直接填充的，而onPreviewFrame需要经过JNI 回调到Java层才能处理，这里是有时间差的。SurfaceTexture在Native层直接填充数据，onPreviewFrame的数据则还需要从Service回调到JNI层。理论上SurfaceTexture 要快一点。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: charles <notifications@github.com>
发送时间: Thursday, March 21, 2019 10:16:24 AM
收件人: CainKernel/CainCamera
抄送: 黄文君; Mention
主题: [CainKernel/CainCamera] onPreviewFrame 和 onFrameAvailable 回调的时序问题 (#50)


@CainKernel<https://github.com/CainKernel> 你好， 我看到在RenderThread中，你是收到相机的回调方法onPreviewFrame之后调用requestRender，然后开始drawFrame的，在drawFrame中调用了updateTexImage。但是updateTexImage需要在SurfaceTexture的一帧数据可用之后调用。这里能够保证onFrameAvailable在相机回调onPreviewFrame之前就被调用了吗？

―

**Comment by Greatkingcj** [comment]
这两个过程是异步的吧， 所以为了保险一点是不是应该在OnFrameAvailable中requestRender呢？我试了一下，在onFrameAvailable中调用requestRender也是可以的

**Comment by CainKernel** [comment]
onFrameAvailable里面进行更新才更不能保证同步。你是没试过低端手机上是怎样的情况。onPreviewFrame回调的数据要经过人脸关键点处理。优秀的SDK大约需要消耗30ms左右，而有些SDK则需要消耗将近40ms。这时候有可能出现SurfaceTexture的刷新率是30fps，而onPreviewFrame只有20fps的情况，人脸关键点回调的数据完全对不上的情况。这个地方需要做同步的地方还是比较难的。我的项目这么使用，主要是考虑到这一点。onPreviewFrame没通知SurfaceTexture 调用updateTexImage，这样SurfaceTexture中的画面是不会更新的，使用onPreviewFrame来刷新能保证只有前后两帧的差距。不过这里还是会对彩妆部分造成一定的抖动现象

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: charles <notifications@github.com>
发送时间: Thursday, March 21, 2019 11:03:37 AM
收件人: CainKernel/CainCamera
抄送: 黄文君; Mention
主题: Re: [CainKernel/CainCamera] onPreviewFrame 和 onFrameAvailable 回调的时序问题 (#50)


这两个过程是异步的吧， 所以为了保险一点是不是应该在OnFrameAvailable中requestRender呢？我试了一下，在onFrameAvailable中调用requestRender也是可以的

―
