### ISSUE TITLE
请问你的动态贴纸json如何构建的呢

### ISSUE THREAD

**Issue by LJRice** [CainKernel/CainCamera#54]

**Comment by CainKernel** [comment]
我建议你去看我简书的《Android 美颜类相机开发汇总》系列文章 , [《Android 美颜类相机开发汇总》第四章 Android OpenGLES 动态贴纸实现](https://www.jianshu.com/p/122bedf3a17e) 。里面有json的解析。普通动态贴纸基本需要涉及几个参数 —— 贴纸的类型、名称、宽高、偏移量、相对于人脸的缩放比例、人脸的宽度、贴纸相对于人脸中心点、贴纸帧数、贴纸一帧渲染的时长、是否带音乐、是否循环、贴纸支持的最大人脸数等。这些都是常用的。简单来说就是，贴纸中心在人脸关键点的锚点和偏移量、贴纸相比人脸多大比例、贴纸有多少张，每张贴纸时间间隔是多长，贴纸支持多少个人脸。关键json如何构建的问题，我只能说自行实现。我这边就是自行实现的。你也可以用其他方式来实现，根据你的实际情况来构建，甚至你也可以用XML来描述，这都不影响。设定好参数之后，你可以在PC上写个工具构建一套自动打包的工具的。这样就不用手动写json了。
