### ISSUE TITLE
What are the 106 Facial Landmark Points?

### ISSUE THREAD

**Issue by peacherwu** [CainKernel/CainCamera#55]
瘦脸，大眼代码中很多地方使用了106个点cartesianPoints[xxx]的数组，不知道这个数组对应的landmark points分别是什么，很难理解；次序好像和https://console.faceplusplus.com/documents/13207488 的说明不同。多谢啦！

**Comment by CainKernel** [comment]
关键点SDK的106个点就是Face++给出来的。详情请看facedetectlibrary中的assets目录中的标记图。这是Face++ SDK中的图，https://github.com/FacePlusPlus 这是Face++在github上的主页，SDK是从这里来的。你先搞清楚Face++的SDK是怎么用的再说。目前瘦脸大眼部分用了整图三角剖分的思想，逐个三角形做形变处理来实现的。理论上目前市面上的美颜类相机基本都是这种思路。cartesianPoints[106] 就是关键点在笛卡尔坐标系上的坐标。瘦脸大眼你也可以用其他方式做处理，思路基本一致，都是调整图像形变的。
