### ISSUE TITLE
请问想要编辑视频的时候使用美颜该怎么做?还有就是给视频录音,有什么好的方案呢?

### ISSUE THREAD

**Issue by roybill** [CainKernel/CainCamera#56]

**Comment by CainKernel** [comment]
美颜部分可以将yuv、rgba图像数据传递给人脸关键点SDK做关键点识别，把结果传进来就好，我已经构建了一个滤镜链表，你可以把美颜部分的滤镜组合起来放到一个渲染结点中处理，把处理后的纹理id传递到下一个渲染结点处理就好。这是目前我项目的整体思路，你可以用其他方式来处理，甚至用java和 MediaCodec处理，不一定要用C++和ffmpeg来处理的。

你说的“给视频录音”是什么意思？添加背景音乐吗？如果是指添加背景音乐的话，编辑页面的实时预览是分开两个播放器来处理的，合成阶段，ffmpeg这边的方案通常是音频解码后得到AVFrame，然后走AVFilter进行混音处理，在混音之前，你还可以做视频原声和背景音乐的音量调节。然后，将混音后的数据取出来，走合成流程。如果是用Java层的MediaCodec来处理的话，先解码得到PCM数据，然后通过PCM混音算法处理，然后将混音后的PCM数据再与视频流合成新的视频。这里涉及比较复杂的同步问题要处理的，比如音视频同步问题，PCM混音长度问题等等都是要你自己做处理的。这也是段视频编辑的最复杂的地方所在了。我最近换了家公司，还在入职阶段，短时间内要适应环境熟悉代码啥的，估计比较忙，合成功能我这边还没时间处理，等忙完这段时间我再把剩下的给视频特效、滤镜、添加背景音乐、音量调节等功能做完。这个你先根据以上思路自行实现。
