### ISSUE TITLE
基于DynamicStickerNormalFilter类渲染自定义的贴纸问题

### ISSUE THREAD

**Issue by hu-ping** [CainKernel/CainCamera#57]
作者，你好，我基于你的DynamicStickerNormalFilter类进行自定义的贴纸的绘制，我在渲染一个帽子的时候，这个帽子闪的厉害，可能的原因是什么了？会是这些参数设置的问题吗？offsetX， offsetY， baseScale， startIndex， endIndex？大佬方便留下你的qq，或者是微信吗？

**Comment by hu-ping** [comment]
感觉就是2个texture渲染到一个frambuffer中出现的闪屏问题。

**Comment by hu-ping** [comment]
是不是深度的问题？

**Comment by CainKernel** [comment]
这个跟深度没啥关系, 我就没用到深度的知识. 如果在glBindFrameBuffer(0) 之前做渲染,那么不可能出现闪屏现象的,任你怎么画都可以. 你去检查一下了渲染的流程吧.我原来的绘制流程就是多个动态贴纸逐个绘制到同一个FBO上的逻辑,并没有出现这种情况.

**Comment by hu-ping** [comment]
你好，我把cat中的ear_000.png替换为我自己的一个帽子贴图，然后这个帽子就不停的闪。帽子的分辨率是480*303，原来ear的分辨率是454 *150

**Comment by hu-ping** [comment]
sorry，是我替换的问题，我只替换了000，没有替换001
