### ISSUE TITLE
视频预览页面拍照和拍视频比较占内存

### ISSUE THREAD

**Issue by lixiong4111** [CainKernel/CainCamera#59]

**Comment by bang919** [comment]
感觉有点卡，我看其他GLES20相机好像没这么卡，是什么原因呢。。。

**Comment by CainKernel** [comment]
预览拍照和拍视频不是维持在200-250<tel:200250>M的内存之间么？这个算比较占内存？如果你比较过抖音快手微视等短视频APP以及各种美颜类相机APP的内存占用，内存占用应该没有比我写的更低了吧，整个Java层的滤镜框架还有不少可以处理，这种涉及OpenGL的处理，如果想更省内存，你可以把渲染逻辑全部放到C/C++中进行处理，把中途涉及的对象全部变成结构体来处理。



发自我的小米手机
在 bang919 <notifications@github.com>，2019年4月23日 下午2:39写道：

感觉有点卡，我看其他GLES20相机好像没这么卡，是什么原因呢。。。

**Comment by CainKernel** [comment]
“感觉有点卡”，这个你要在定量的前提下比较才有用，别的相机在低端机上不一定是720P渲染的，我也可以缩小成更小的纹理分辨率进行处理，fps会更高，不过没啥意义。这个不是靠感觉来评判的。根据我这边的测试，高通625超过20fps，高通660稳定超过25fps，只要把滤镜的压缩包全替换成LUT方式处理，能稳定达到28fps以上，这也算卡么？另外预览画面帧率还跟光照环境有关，比如小米6X的前置摄像头在黑暗环境下，相机本身出来的帧率就只有20fps左右，这跟APP没任何关系，所以你说的“好像”，“感觉”，至少得放在统一条件下才能做比较。另外一个问题，渲染线程可以做定时刷新，我这边是按when dirty方式来做渲染处理的，GLSurfaceView的continuously方式并没有实现，你可以添加这种刷新方式。



发自我的小米手机
在 bang919 <notifications@github.com>，2019年4月23日 下午2:39写道：

感觉有点卡，我看其他GLES20相机好像没这么卡，是什么原因呢。。。
