### ISSUE TITLE
so文件以及minSdk问题

### ISSUE THREAD

**Issue by HeYongRui** [CainKernel/CainCamera#60]
看见项目里设置的是armeabi-v7a模式，如果想只兼容armeabi的话armeabi-v7a的so文件可以用到armeabi里吗？不能的话有没有armeabi的so文件呢？另外看到根据openGLES版本设置的minSdk很高为21，那怎么改能使minSdk小一点呢？谢谢，很急。

**Comment by CainKernel** [comment]
不行，armeabi 跟 armeabi-v7a并不完全兼容。你可以去搜索相关的差异。OpenGLES的minSDK可以设置低版本的，我这边支持Android5.0以上只是为了方便使用Native层的FFmpeg + AMediaCodec实现硬解码而已。而且，我不太了解你说的minSDK = 21 很高是几个意思，目前超过90%的设备都是Android5.0以上的了，API低于18的设备连MediaCodec支持都成问题。现在都Android pie了。。。
