### ISSUE TITLE
请教作者几个问题

### ISSUE THREAD

**Issue by oksimple** [CainKernel/CainCamera#63]
感谢作者弄了这么好的库。
问题：
1.旋转屏幕后 为人脸贴的兔子耳朵跑飞了，这是什么问题造成的？
2.还有人脸识别的时候我看加了锁这样 会不会效率很低呢？会不会出现一帧一帧的移动卡顿啊？
3.Face++的识别库现在能检测多少个点呢？ 如果我替换成其他开源方案 难度如何？

**Comment by CainKernel** [comment]
1、这个应该是人脸SDK给出的姿态角不对导致，目前Face++这里做得没商汤好， 你仔细检查就会发现，抬头侧脸的话，正面也照样出现这样的问题。姿态角误差太大了，抬头超过20度了，给出的角度只有10度不到。这里我在代码里面有说明。
2、效率是可以得到保证的，只要你处理的逻辑不超过30ms就好。比较耗时的磨皮，效率上面已经解决了的。后面绘制贴纸啥的基本没啥性能问题的。这里拆分成两个线程，主要是做并行化处理，需要添加锁进行同步处理，目前大部分耗时都在人脸关键点识别上吧。
3、目前使用的是市面上商用常用的106个关键点，另外我在这基础上扩建了几个点。如果你想替换的话，难度也不大，我这边将人脸SDK拆分成了两个库，一个是第三方SDK检测库facedetectlibrary， 另外一个是关键点归一化的库landmarklibrary，你替换facedetectlibrary之后，主要是改动这两个库就好。替换难度也没多少吧，除了需要你计算额外几个关键点，重新构建人脸三角剖分就行。除了瘦脸那里需要做些修改之外，其他的基本不需要怎么大改动。
