### ISSUE TITLE
请教作者几个问题有偿解决

### ISSUE THREAD

**Issue by yang2250211** [CainKernel/CainCamera#64]
我这边有个项目 采用GlSurfaceView 显示  MediaCodec解码 在4.4以上的机器上 录制视频运行正常 但是在4.4的系统出现录制视频 速率过快 帧数过高 这个问题困扰了 我很久 希望作者有时间 能给点参考意见 如果解决成功 可以提供1000元 给作者

**Comment by CainKernel** [comment]
钱就不用了，我写这个项目也不是为了钱。你可以往几个方向去考虑。以前的Android 系统 MediaCodec 功能比较受限，比如会出现录制的视频固定是25fps，正常逻辑计算出来的时间戳对不上等。你的情况，看着像是低版本的Android系统中MediaCodec在某些地方的时间戳计算有误导致的。我也不太清楚你具体怎么实现的，这个要具体问题具体分析才行。

**Comment by akfheaven** [comment]
跟作者咨询一下，YY开播上面的磨皮效果非常好，感觉不是用高斯模糊，能提一些思路么，感激不尽。@CainKernel

**Comment by CainKernel** [comment]
@akfheaven 磨皮效果非常好也是调参的结果。目前实时磨皮就两种方案能用的，其他的磨皮算法，预览帧率方面都达不到要求。

**Comment by akfheaven** [comment]
哪两个方案能说说么@CainKernel

**Comment by CainKernel** [comment]
@akfheaven 第一种就是我项目正用的美颜方案，另外一种就是filterlibrary里面的GLImageOldBeautyFilter里面的方案，目前市面上90%的相机都是这两种磨皮方案以及变种，剩下的都是调参。什么双边保留磨皮法之类的，基本上达不到实时预览的性能，用了磨皮只剩十几帧，其他功能都没法做了。

**Comment by akfheaven** [comment]
@CainKernel Thanks!
