### ISSUE TITLE
大神，关于给图片中人物头发换颜色，这种功能能做吗

### ISSUE THREAD

**Issue by peach-djf** [CainKernel/CainCamera#65]

**Comment by CainKernel** [comment]
这个功能有两种方式，一种是基于发色检测来做染色，但是效果非常差， 目前市面上基本不会用这个方案。另外一种是基于深度学习的方式，生成一个蒙版然后就跟彩妆的处理一样，仅对头发的蒙版区域做处理，这是目前市面上实现染发功能的APP的通用方案，能做到实时渲染的效果，不过这个要SDK支持，自己做并不现实。能做是能做，但SDK价格都比较贵。

**Comment by peach-djf** [comment]
收到你的回复我非常高兴，也对这个方面多了一分的了解。你说第三方sdk能做到，是face++这种平台吗，如果要做，是不是找客服，商务定制呢？
