### ISSUE TITLE
您好，关于美颜请教下

### ISSUE THREAD

**Issue by AworldIcon** [CainKernel/CainCamera#66]
您好，当体验demo的时候发现，磨皮最大，美白也最大值，但是当光线不足的时候没有美颜效果，请问该怎么处理呢，试着修改了配置文件中的算法，但是没有效果，因为才开始学这方面，所以麻烦您了。

**Comment by CainKernel** [comment]
光线不足的情况下，不管哪种美颜算法都没用。目前市面上的相机，磨皮算法都大同小异，就是调整参的区别。通常的做法就是补光，调整亮度等处理。这种事情没有统一的处理方案。

**Comment by AworldIcon** [comment]
您好是不是可以在阴影和黑暗区域做补白高光的处理呢？应该怎么实现呢？之前发现在光线不足或者黄色光照下，预览图像就没有美颜效果了。
