### ISSUE TITLE
关于相机的比例问题

### ISSUE THREAD

**Issue by HeYongRui** [CainKernel/CainCamera#67]
你好，很感谢作者贡献的这个开源，对于一些需要的开发者提供了很大的便利。我碰到两个问题想请教一下。

一是关于相机比例的，要实现1:1  4:3  full等比例，但有些机型的相机预览尺寸和拍照尺寸不一定比例相等，(例如找出最合适1:1的：机型1：PreviewSize的宽高为352，288，PictureSize的宽高为1024,1024；机型2：PreviewSize和PictureSize的宽高都为176，144)。这两种机型的PreviewSize比例一样，我想通过改变纹理坐标的方式使1:1不变形，于是我将纹理坐标改为
textureCoord = new float[] {
                0f, 0.091f,
                1f, 0.091f,
                0f, 0.909f,
                1f, 0.909f
        };，但是一种机型可以正常显示，另一种不可以，这是为什么以及有什么办法吗。

二是如果想编辑视频的话，怎样添加贴纸，是不是openGL快一点，之前用ffmpeg但是超级慢，有其他办法吗。

**Comment by CainKernel** [comment]
相机比例问题可以参考之前的issue，有过讨论。另外，添加贴纸这些基本上跟ffmpeg没啥关系，这些都是图像处理，不是音视频编解码部分的内容。因此，想要快速添加贴纸、滤镜这些，需要重走OpenGL渲染流程，然后提取纹理数据进行编码，也就是跟录制没啥区别。
