### ISSUE TITLE
拍照裁剪时调用EglSurfaceBase中的getCurrentFrame方法耗时长！！！

### ISSUE THREAD

**Issue by josh2028** [CainKernel/CainCamera#68]
拍照裁剪时调用EglSurfaceBase中的getCurrentFrame方法耗时长，GLES30.glReadPixels这个把GPU的数据转成到内存的过程太长了，有什么好的方法提高性能呢？？？

**Comment by CainKernel** [comment]
本身调用这个方法耗时就比较长。想快的话，你可以用ImageReader提取

**Comment by josh2028** [comment]
有例子吗？能发我看一下吗？
