### ISSUE TITLE
CainShortVideoEditor问题

### ISSUE THREAD

**Issue by HeYongRui** [CainKernel/CainCamera#69]
CainShortVideoEditor运行自定义命令时，Android 9会出现闪退， FORTIFY: pthread_mutex_lock called on a destroyed mutex (0xc8f1771c) ，是Pie的限制非系统API调用的问题吗，有什么解决办法吗？

**Comment by CainKernel** [comment]
应该跟系统版本没啥关系，可能是个BUG
