### ISSUE TITLE
您好，编译不过，一直报错  /bin/sh: -UHAVE_CONFIG_H: command not found， 能帮忙看下吗

### ISSUE THREAD

**Issue by rarest** [CainKernel/CainCamera#7]
clang++  --target=armv7-none-linux-androideabi --gcc-toolchain=/Dev/android-sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 --sysroot=/Dev/android-sdk/ndk-bundle/sysroot  -Dpusher_EXPORTS -I../../../../src/main/cpp/libpolarssl/include -I../../../../src/main/cpp -I../../../../src/main/cpp/librtmp -isystem /Dev/android-sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem /Dev/android-sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -isystem /Dev/android-sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -isystem /Dev/android-sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=19 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-integrated-as -mthumb -Wa,--noexecstack -Wformat -Werror=format-security  -std=c++11 -fPIC -fpermissive -std=c++11 -D__STDC_CONSTANT_MACROS -DFIXED_POINT -DUSE_KISS_FFT -DEXPORT=; -UHAVE_CONFIG_H  -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/pusher.dir/src/main/cpp/pusher/cain_pusher.cpp.o -MF CMakeFiles/pusher.dir/src/main/cpp/pusher/cain_pusher.cpp.o.d -o CMakeFiles/pusher.dir/src/main/cpp/pusher/cain_pusher.cpp.o -c /CainCamera/pushlibrary/src/main/cpp/pusher/cain_pusher.cpp
 clang++: error: no input files
 /bin/sh: -UHAVE_CONFIG_H: command not found

**Comment by CainKernel** [comment]
我手上没有Mac电脑，无法做测试。看log似乎是pushlibrary的CmakeLists.txt 中CPP文件路径对不上的原因，找不到输入文件。你先把这个module注释掉吧。RTMP推流部分的代码，你可以暂时去掉，这个module的代码只在Camera的测试页面的推流有用到，去掉不影响Camera 的功能。或者，你想保留pushlibrary的话，看看CmakeLists.txt 中的源码中的路径是否跟目录对得上。我这边windows 和Linux环境下都是正常运行。另外一个问题就是，你检查一下是否导入AS工程的时候，导入的时CainCamera还是里面的camera module，直接导入CainCamera 目录也不对的，CainCamera里面还有一个VideoPlayer工程，是用来编写测试基于FFmpeg播放器的，如果直接导入CainCamera目录，这个也会出现类似的问题。你从这些方面入手看看能不能编译通过。

**Comment by rarest** [comment]
@CainKernel 我把pushlibrary module下的CmakeLists.txt里买呢的CMAKE_CXX_FLAGS里面 -DEXPORT=""  删除就ok，或者pusher 改成STATIC也OK，请教下这是什么原因？
