### ISSUE TITLE
视频特效Android实现方案问题

### ISSUE THREAD

**Issue by austin98x** [CainKernel/CainCamera#76]
请问，您之前实现的VideoEditRenderEngine方案，播放器如何把数据通过updateYUVData或者setBGRAData传到里面去来实现特效滤镜？
该方案我看您删掉了，后来用native层实现特效了。但是我想学习下您的android层实现滤镜特效方案如何走通的。

**Comment by CainKernel** [comment]
Android层的滤镜特效方案可以通过Java层走的，我这边主要是因为自研的播放器是基于FFmpeg + OpenGL实现的，OpenGL是用的Native层的EGLContext，如果再在Java层创建一个的话，会有冲突的，因此这里的解决方案要么就是改播放器，要么把特效处理放到Native层进行处理。在这两种方案中，我选择了后者。你也可以改播放器，将视频数据从Native层回传到Java层，然后通过OpenGL进行渲染，这样就可以通过Java层实现了。或者，你也可以不用FFmpeg做播放器，通过MediaCodec实现播放器也是可以的。方案有很多，我这里选择的方案主要是为了尽可能地复制实现抖音的处理方案而已。

**Comment by austin98x** [comment]
需要定制播放器太麻烦了，如果只是用Android的MediaPlayer做播放器，然后再java层做OpenGL特效处理该如何做呢？

**Comment by austin98x** [comment]
还想请教个问题。目前我看到java层做特效处理有两种方案，１是继承GLSurfaceView并且继承他的Renderer，在回调函数onDrawFrame中做想要的特效绘制。２是用SurfaceTexture并且通过updateTexImage()函数调用来获取TextureId，然后再绘制想要的特效。

**Comment by CainKernel** [comment]
定制播放器都不做的话，基本上很难做个什么东西出来。哪怕做出来也只是做出来功能，在各方面都达不到理想的状态，更别说要做复杂功能的SDK了，音视频编解码就不是Java擅长的东西。你说的onPreviewFrame这个是相机的，跟你前面问的定制播放器不是一回事。
