### ISSUE TITLE
abi so文件请教

### ISSUE THREAD

**Issue by HeYongRui** [CainKernel/CainCamera#78]
你好，请问一下，目前这个so文件好像只有armeabi-v7a的，那可不可以直接拷贝到arm64-v8a或者armeabi里呢，是否兼容？或者能不能麻烦编译个64位的so呢？以及cmake的配置是否也需要加DANDROID_ABI呢？急！thx~

**Comment by CainKernel** [comment]
不能直接复制。v7a和v8a不兼容的。v8a是AArch-64的，跟v7a不是一个东西。so库你可以自己用Linux编译一个，编译脚本改起来也不是什么难事。目前只有libffmpeg.so需要自己单独编译，libyuv.so目前是还没来得及用上。
