### ISSUE TITLE
导入Android Studio编译出错！！

### ISSUE THREAD

**Issue by ruijun** [CainKernel/CainCamera#8]
hello @CainKernel ， 导入项目到AS后，编译出现下面的错误，切换了ndk版本也不可以。想问下是不是有其他地方需要特殊配置的？
```
D:\DevTools\ndk\android-ndk-r13\toolchains\llvm\prebuilt\windows-x86_64\lib64\clang\3.8.256229\include\stdatomic.h
Error:(156, 11) fatal error: 'uchar.h' file not found
```

**Comment by CainKernel** [comment]
更新一下你的NDK以及编译工具，NDK R13有Bug，FFmpeg用了uchar.h文件，但R13会提示找不到这个文件。我用的是AS下载的最新版，好像是R16吧。



发自我的小米手机
在 Jimson Liang <notifications@github.com>，2018年3月12日 下午4:40写道：

hello @CainKernel<https://github.com/cainkernel> ， 导入项目到AS后，编译出现下面的错误，切换了ndk版本也不可以。想问下是不是有其他地方需要特殊配置的？

D:\DevTools\ndk\android-ndk-r13\toolchains\llvm\prebuilt\windows-x86_64\lib64\clang\3.8.256229\include\stdatomic.h
Error:(156, 11) fatal error: 'uchar.h' file not found

**Comment by ruijun** [comment]
嗯嗯，用NDK R16就可以了。想问下图片编辑与视频编辑功能什么时候完成的呢？

**Comment by CainKernel** [comment]
我也不知道什么时候能完成。一个人做有点慢，我也不是什么时候都有空，有空我就一点一点功能地加上去。我最近在做图片编辑部分，视频编辑部分估计没那么快，播放器还没搞好，后面渲染和转码没法继续做下去。



发自我的小米手机
在 Jimson Liang <notifications@github.com>，2018年3月12日 下午5:44写道：

嗯嗯，用NDK R16就可以了。想问下图片编辑与视频编辑功能什么时候完成的呢？
