### ISSUE TITLE
请问支持X86内核吗

### ISSUE THREAD

**Issue by newer-android** [CainKernel/CainCamera#82]
您好，请问该功能支持X86内核吗

**Comment by CainKernel** [comment]
x86内核的话，你可以自己编译一个libffmpeg.so。目前涉及的代码功能本身不分哪个平台，只跟Android版本相关，并且功能代码本身是全开源的，需要改动的话，可以自己动手修改。

**Comment by newer-android** [comment]
谢谢您的回复，因为是初学者才接触这方面的知识，在使用过程中遇到了一个问题，选择滤镜相机—>选择左侧的贴纸，结果点击第一个猫耳没有反应，第二个星星图案显示出来但是不随着面庞移动，点击后面三个都起作用，我已经将FaceppConstraints.Java中的APP_KEY和APP_SECRET换成自己申请的值，请问还需要其他的配置吗？

**Comment by CainKernel** [comment]
到Face++官网注册个key，然后绑定bundle即可。正式商用，请换商业版或者更换其他SDK，这里只是介绍整体的开发过程。



发自我的小米手机
在 newer-android <notifications@github.com>，2019年7月10日 下午1:39写道：

谢谢您的回复，因为是初学者才接触这方面的知识，在使用过程中遇到了一个问题，选择滤镜相机—>选择左侧的贴纸，结果点击第一个猫耳没有反应，第二个星星图案显示出来但是不随着面庞移动，点击后面三个都起作用，我已经将FaceppConstraints.Java中的APP_KEY和APP_SECRET换成自己申请的值，请问还需要其他的配置吗？

**Comment by newer-android** [comment]
好的 谢谢 我是运行Demo，了解一下整体流程，谢谢您的帮助
