### ISSUE TITLE
下载后运行保存不了呢？

### ISSUE THREAD

**Issue by mankind-evolve** [CainKernel/CainCamera#84]
你好，我下载下来运行，发现视频都 保存不了。不知道是什么原因？

**Comment by CainKernel** [comment]
视频编辑合成部分目前还没时间做。下周末开始计划会对播放器进行改造，合成部分目前还没时间弄，也不在短期内的计划中，要等播放器改造完成才会进入下一步的工作。目前工作日是没时间管这边的，抱歉。

**Comment by mankind-evolve** [comment]
加油。小哥。你代码写的很棒  希望继续完善，提高我国音视频行业的整体水平
