### ISSUE TITLE
开源关键点检测

### ISSUE THREAD

**Issue by chaishuanzhu** [CainKernel/CainCamera#86]
大佬，现在有开源的人脸关键点检测，替换Face++好搞吗？
https://github.com/zeusees/HyperLandmark

**Comment by chaishuanzhu** [comment]
研究了下，和Face++比起来还是有点差

**Comment by yuxingfafu** [comment]
@chaishuanzhu 哥们，你这个后面可以替换么？我试了下有问题，预览都点问题出来一卡一卡的，预览的图像没有全部处理

**Comment by chaishuanzhu** [comment]
> @chaishuanzhu 哥们，你这个后面可以替换么？我试了下有问题，预览都点问题出来一卡一卡的，预览的图像没有全部处理
只是看了一下，还没有投入使用。

**Comment by yuxingfafu** [comment]
@chaishuanzhu 集成进去了？FaceTracker类的internalTrackFace方法方便参考看下的不？我是改这个类的这个方法

**Comment by chaishuanzhu** [comment]
@yuxingfafu 电脑重装了一次，那个项目找不到了。
