### ISSUE TITLE
编译报fatal error: 'uchar.h' file not found

### ISSUE THREAD

**Issue by xwtao** [CainKernel/CainCamera#9]
E:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\lib64\clang\3.8.275480\include\stdatomic.h
Error:(150, 11) fatal error: 'uchar.h' file not found
这是什么原因呢

**Comment by CainKernel** [comment]
请升级NDK的版本。这是NDK的Bug，升级到最新版本NDK R16就没问题了。



发自我的小米手机
在 xwtao <notifications@github.com>，2018年3月18日 下午3:03写道：

E:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\lib64\clang\3.8.275480\include\stdatomic.h
Error:(150, 11) fatal error: 'uchar.h' file not found
这是什么原因呢
